### PR TITLE
Fixes #253

### LINKED ISSUE #253: WhitelistServiceImpl.whitelistEnabledForState
I think this is implemented wrong.  It looks like it is querying the whitelist_entry table and not the whitelisted_states table.  If that is the case then I don't think the _state table is ever used.

### PR DESCRIPTION
**Pull request by larubbio**
The check for whitelist being enabled for a state was looking in the wrong table.

### CODE REVIEW

File: flw/src/test/java/org/motechproject/nms/flw/osgi/WhiteListServiceBundleIT.java [hunk 1]
```diff
@@ -131,4 +131,38 @@ public void testStateWithWhitelistInvalidNumber() throws Exception {
         boolean result = whitelistService.numberWhitelistedForState(whitelistState, NOT_WHITELIST_CONTACT_NUMBER);
         assertFalse(result);
     }
+
+    // Test state with whitelist, number not in list
```
Comment (koshalt) [inline flw/src/test/java/org/motechproject/nms/flw/osgi/WhiteListServiceBundleIT.java]: does this comment need to be updated?

Comment (larubbio) [inline flw/src/test/java/org/motechproject/nms/flw/osgi/WhiteListServiceBundleIT.java]: yes. :(

Comment (llavoie) [inline flw/src/test/java/org/motechproject/nms/flw/osgi/WhiteListServiceBundleIT.java]: If it's easier, you can just update the comment using the github online editor and commit it.
